SELECT *
FROM DEPT

SELECT ENAME,JOB,HIREDATE,EMPNO
FROM EMP

SELECT ENAME,SAL,SAL*12 AS ANNUALSAL
FROM EMP

SELECT ENAME + ',  ' + JOB AS EMPLOYEETITLE
FROM EMP

SELECT DISTINCT JOB
FROM EMP

SELECT ENAME,SAL
FROM EMP
WHERE SAL > 2850;

SELECT ENAME,DEPTNO
FROM EMP
WHERE ENAME='SMITH';

SELECT E.ENAME,J.STARTDATE,E.JOB
FROM EMP E
FULL OUTER JOIN
JOBHIST J
ON(E.EMPNO=J.EMPNO)
WHERE E.HIREDATE BETWEEN '1981-02-20' AND '1981-05-01';

SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO IN(10,30)
GROUP BY ENAME,DEPTNO
ORDER BY ENAME

SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1982-01-01' AND '1982-12-31'

SELECT ENAME,JOB
FROM EMP
WHERE MGR IS NULL 

SELECT CAST(GETDATE() AS DATE) AS DATE;

SELECT E.ENAME,E.HIREDATE,J.HIREDATE
FROM EMP E
FULL OUTER JOIN
EMP J
ON E.EMPNO=J.MGR
WHERE E.HIREDATE < J.HIREDATE

SELECT COUNT(MGR)
FROM EMP

SELECT *
FROM EMP
WHERE DEPTNO IN (20,30,40);

select ENAME
FROM EMP
WHERE ENAME LIKE 'T%R';

SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO=30;


SELECT FORMAT(HIREDATE,'dd-MM-yy') AS 'FORMATED DATE'
FROM EMP;


SELECT FORMAT(HIREDATE,' dd MMMM, yyyy')
FROM EMP
WHERE JOB LIKE 'ANALYST';

SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE LIKE '_____12___';

SELECT DEPTNO,JOB,AVG(SAL*12)
FROM EMP
GROUP BY DEPTNO,JOB;

SELECT COUNT(DEPTNO)
FROM EMP
WHERE DEPTNO='30' AND COMM > '0'AND SAL>'0';

SELECT AVG(SAL) AS AVERAGE,MIN(SAL) AS MINIMUM,MAX(SAL) AS MAXIMUM
FROM EMP
WHERE JOB='CLERK' OR JOB='MANAGER';

SELECT COUNT(DEPTNO) AS COUNTING,DEPTNO
FROM EMP
WHERE JOB='CLERK'
GROUP BY DEPTNO
HAVING COUNT(DEPTNO)>1;

SELECT ENAME,SAL
FROM EMP
WHERE SAL < (SELECT SAL*0.3
              FROM EMP
			  WHERE JOB='PRESIDENT');

SELECT COUNT(D.LOC)
FROM EMP E
RIGHT OUTER JOIN
DEPT D
ON(E.DEPTNO=D.DEPTNO)
WHERE D.LOC='CHICAGO'

SELECT E.ENAME, D.LOC
FROM EMP E
RIGHT OUTER JOIN
DEPT D
ON(E.DEPTNO=D.DEPTNO)
WHERE D.LOC='CHICAGO'

SELECT E.ENAME, D.LOC
FROM EMP E
FULL OUTER JOIN
DEPT D
ON(D.DEPTNO=E.DEPTNO)
ORDER BY D.LOC

SELECT COUNT(DISTINCT EMPNO) AS EMPLOYEES,COUNT(DISTINCT DEPTNO) AS DEPATMENTS
FROM EMP

SELECT AVG(E.SAL),E.EMPNO
FROM EMP E
LEFT OUTER JOIN
DEPT D
ON(D.DEPTNO=E.DEPTNO)
GROUP BY EMPNO,SAL


SELECT COUNT(DNAME)
FROM DEPT

SELECT D.DEPTNO,D.DNAME,D.LOC,SUM(E.COMM),SUM(E.SAL)
FROM EMP E
LEFT OUTER JOIN
DEPT D
ON(D.DEPTNO=E.DEPTNO)
GROUP BY D.DEPTNO,D.DNAME,D.LOC;

SELECT ENAME,JOB,SAL*12
FROM EMP

SELECT ENAME,JOB,COMM
FROM EMP
WHERE COMM IS NULL

SELECT ENAME,JOB,COMM
FROM EMP
WHERE COMM IS NOT NULL

SELECT ENAME,JOB,SAL
FROM EMP
WHERE ENAME LIKE '__R%'

SELECT ENAME,JOB,SAL
FROM EMP
WHERE ENAME LIKE '_____'

SELECT ENAME,JOB,SAL
FROM EMP
WHERE ENAME NOT LIKE '_____'

SELECT ENAME,JOB,SAL
FROM EMP
WHERE ENAME LIKE '%AR%'

SELECT ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE DEPTNO='30'
ORDER BY SAL

SELECT ENAME,SAL 
FROM EMP
WHERE SAL BETWEEN 1250 AND 1600

SELECT ENAME,SAL 
FROM EMP
WHERE SAL < 1250 OR SAL > 1600

SELECT SUM(SAL) AS TOTALSALARY
FROM EMP

SELECT COUNT(JOB)
FROM EMP
WHERE JOB IS NOT NULL

SELECT MIN(SAL) AS MINIMUM, MAX(SAL) AS MAXIMUM
FROM EMP

SELECT EMPNO AS EMP#,ENAME AS EMPLOYEE, SAL AS SALARY, JOB ,HIREDATE AS 'DATE OF HIRE',COMM AS COMMISSION,DEPTNO AS 'DEPART NO',MGR AS MGRNO
FROM EMP

SELECT MIN(HIREDATE) AS EARLIEST,MAX(HIREDATE) AS LATEST
FROM EMP

SELECT COUNT(DEPTNO)
FROM EMP
WHERE DEPTNO='10'

SELECT E.ENAME,E.JOB
FROM EMP E
LEFT OUTER JOIN
DEPT D
ON(E.DEPTNO=D.DEPTNO)
WHERE D.LOC='NEWYORK' AND E.COMM >10

SELECT FORMAT(HIREDATE,'dddd MMMM dd, yyyy') AS 'DAY MONTH DD, YYY',
FORMAT(HIREDATE,'dy dd MMM yyyy') AS 'DY DD Mon YYYY',
FORMAT(HIREDATE,'dddd dd\t\h MMMM, yyyy') AS 'Day ddth Month YYYY'
FROM EMP;