const members=[
    {
        id:1,
        name:'Shashank',
        email:'shashankmv78@gmail.com',
        status:'active'
    },
    {
        id:2,
        name:'Shashank',
        email:'shashankmv78@gmail.com',
        status:'active'
    },
    {
        id:3,
        name:'Shashank',
        email:'shashankmv78@gmail.com',
        status:'active'
    },
];
module.exports=members;